export const caseStudies = [
  {
    id: 'hotel-marrakech',
    tag: 'Case Study #1',
    tagColor: 'accent-primary',
    title: 'Hotel Marrakech Luxe',
    industry: 'Hospitality',
    challenge: 'The client needed a direct booking engine to reduce dependency on Booking.com commissions.',
    solution: 'We built a custom booking flow with real-time availability, payment gateway, and a simple admin to manage rooms and rates.',
    metrics: [
      { value: '+45%', label: 'Bookings' },
      { value: '0.4s', label: 'Load Time' },
      { value: '#1', label: 'Local Rank' },
    ],
    quote: 'SuperSite delivered exactly what we needed. Direct bookings are up and we control our pricing.',
    quoteAuthor: 'Hotel Manager, Marrakech',
  },
  {
    id: 'atlas-ecommerce',
    tag: 'Case Study #2',
    tagColor: 'accent-secondary',
    title: 'Atlas E-Commerce',
    industry: 'E-Commerce',
    challenge: 'Migrating a slow WordPress store to a modern stack with better SEO and conversion.',
    solution: 'Custom Next.js store with AI product recommendations, one-click checkout, and advanced SEO. Data migrated from WooCommerce.',
    metrics: [
      { value: '3x', label: 'Sales' },
      { value: '99', label: 'SEO Score' },
      { value: 'AI', label: 'Recommendations' },
    ],
    quote: 'Our conversion rate tripled. The new site feels premium and loads in a blink.',
    quoteAuthor: 'Founder, Atlas',
  },
  {
    id: 'restaurant-casablanca',
    tag: 'Case Study #3',
    tagColor: 'accent-primary',
    title: 'Restaurant Brand, Casablanca',
    industry: 'Restaurant',
    challenge: 'Needed an online menu, table reservations, and delivery ordering in one place.',
    solution: 'Single responsive site with digital menu, reservation widget, and integration with local delivery partners.',
    metrics: [
      { value: '+60%', label: 'Online Orders' },
      { value: '2.1s', label: 'Load Time' },
      { value: '4.8', label: 'User Rating' },
    ],
    quote: 'We stopped losing orders to slow sites. Everything works on mobile.',
    quoteAuthor: 'Owner, Casablanca',
  },
  {
    id: 'fintech-rabat',
    tag: 'Case Study #4',
    tagColor: 'accent-secondary',
    title: 'FinTech Startup, Rabat',
    industry: 'FinTech',
    challenge: 'Launch a trustworthy, fast landing page to capture leads for a new financial product.',
    solution: 'Landing page with clear value prop, trust badges, lead form, and Calendly integration. Hosted on a fast CDN.',
    metrics: [
      { value: '32%', label: 'Conv. Rate' },
      { value: 'A+', label: 'Security' },
      { value: '<1s', label: 'Load' },
    ],
    quote: 'Professional and fast. We got hundreds of signups in the first month.',
    quoteAuthor: 'Marketing Lead, Rabat',
  },
];
